package com.example.jdbcdemo.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import com.example.jdbcdemo.domain.Sznurowka;

public class SznurowkaManager {
	
	private Connection connection;

	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	
	private String createTableSznurowka = "CREATE TABLE Sznurowka(id bigint GENERATED BY DEFAULT AS IDENTITY," +
			" producent varchar(30), dlugosc integer, kolor varchar(30)," +
			" grubosc integer)";
	
	private Statement statement;
	
	private PreparedStatement addSznurowkaStatement;
	private PreparedStatement deleteSznurowkaStatement;
	private PreparedStatement getAllSznurowkasStatement;
	
	public SznurowkaManager() {
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();

			ResultSet rs = connection.getMetaData().getTables(null, null, null,
					null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Person".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if (!tableExists)
				statement.executeUpdate(createTableSznurowka);

			addSznurowkaStatement = connection
					.prepareStatement("INSERT INTO Sznurowka (producent, dlugosc," +
							" kolor, grubosc) VALUES (?, ?, ?, ?)");
			deleteSznurowkaStatement = connection
					.prepareStatement("DELETE FROM Sznurowka where id = ?");
			getAllSznurowkasStatement = connection
					.prepareStatement("SELECT s FROM Sznurowka s");

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	Connection getConnection() {
		return connection;
	}
	
	public int addSznurowka(Sznurowka s) {
		int count = 0;
		try {
			addSznurowkaStatement.setString(1, s.getProducent());
			addSznurowkaStatement.setInt(2, s.getDlugosc());
			addSznurowkaStatement.setString(3, s.getKolor());
			addSznurowkaStatement.setInt(4, s.getGrubosc());

			count = addSznurowkaStatement.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return count;
	}

}
