package com.example.jdbcdemo.service;

import java.sql.Array;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.example.jdbcdemo.domain.Sznurowka;

public class SznurowkaManager {
	
	private Connection connection;

	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	
	private String createTableSznurowka = "CREATE TABLE Sznurowka(id bigint GENERATED BY DEFAULT AS IDENTITY," +
			" producent varchar(30), dlugosc integer, kolor varchar(30)," +
			" grubosc integer, sklep_id bigint)";
	private String createTableSklep = "CREATE TABLE Sklep(id bigint GENERATED BY DEFAULT AS IDENTITY," +
			" nazwa varchar(30))";
	
	private Statement statement;
	
	private PreparedStatement addSznurowkaStatement;
	private PreparedStatement updateSznurowkaStatement;
	private PreparedStatement deleteSznurowkaStatement;
	private PreparedStatement getAllSznurowkasStatement;
	private PreparedStatement getSznurowkaStatement;
	private PreparedStatement kupSznurowkiStatement;
	private PreparedStatement sprzedajSznurowkeStatement;	
	
	public SznurowkaManager() {
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();

			ResultSet rs = connection.getMetaData().getTables(null, null, null,
					null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Sznurowka".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}
			
			if (!tableExists)
				statement.executeUpdate(createTableSznurowka);

			//Tabela sklep
			tableExists = false;
			while (rs.next()) {
				if ("Sklep".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if (!tableExists)
				statement.executeUpdate(createTableSklep);

			addSznurowkaStatement = connection
					.prepareStatement("INSERT INTO Sznurowka (producent, dlugosc," +
							" kolor, grubosc) VALUES (?, ?, ?, ?)");
			deleteSznurowkaStatement = connection
					.prepareStatement("DELETE FROM Sznurowka where id = ?");
			getAllSznurowkasStatement = connection
					.prepareStatement("SELECT s FROM Sznurowka s");
			updateSznurowkaStatement = connection
					.prepareStatement("UPDATE Sznurowka SET producent = ? , " +
							"dlugosc = ? , kolor = ? , grubosc = ? " +
							"WHERE id = ?");
			getSznurowkaStatement = connection.prepareStatement("Select s from " +
					"Sznurowka s where s.id =?");
			kupSznurowkiStatement = connection.prepareStatement("UPDATE Sznurowka SET sklep_id = ? " +
					"WHERE id in (?)");
			sprzedajSznurowkeStatement = connection.prepareStatement("UPDATE Sznurowka SET sklep_id = null " +
					"WHERE id = ?");

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	Connection getConnection() {
		return connection;
	}
	
	public int addSznurowka(Sznurowka s) {
		int count = 0;
		try {
			addSznurowkaStatement.setString(1, s.getProducent());
			addSznurowkaStatement.setInt(2, s.getDlugosc());
			addSznurowkaStatement.setString(3, s.getKolor());
			addSznurowkaStatement.setInt(4, s.getGrubosc());

			count = addSznurowkaStatement.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return count;
	}
	
	public List<Sznurowka> getAllSznurowki() {
		List<Sznurowka> sznurowki = new ArrayList<Sznurowka>();
	
		try {
			ResultSet rs = getAllSznurowkasStatement.executeQuery();
	
			while (rs.next()) {
				Sznurowka s = new Sznurowka();
				s.setId(rs.getLong("id"));
				s.setProducent(rs.getString("producent"));
				s.setDlugosc(rs.getInt("dlugosc"));
				s.setKolor(rs.getString("kolor"));
				s.setGrubosc(rs.getInt("grubosc"));
				sznurowki.add(s);
			}
	
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return sznurowki;
	}
	
	public Sznurowka getSznurowka(Long id) {
		Sznurowka s = new Sznurowka();
		try {
			getSznurowkaStatement.setLong(1, id);
			ResultSet rs = getSznurowkaStatement.executeQuery();
	
			s.setId(rs.getLong("id"));
			s.setProducent(rs.getString("producent"));
			s.setDlugosc(rs.getInt("dlugosc"));
			s.setKolor(rs.getString("kolor"));
			s.setGrubosc(rs.getInt("grubosc"));

	
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return s;
	}
	
	public void deleteSznurowka(Long id) {
		try {
			deleteSznurowkaStatement.setLong(1, id);

			deleteSznurowkaStatement.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	public void updateSznurowka(Sznurowka s) {
		try {
			updateSznurowkaStatement.setString(1, s.getProducent());
			updateSznurowkaStatement.setInt(2, s.getDlugosc());
			updateSznurowkaStatement.setString(3, s.getKolor());
			updateSznurowkaStatement.setInt(4, s.getGrubosc());
			
			updateSznurowkaStatement.setLong(1, s.getId());

			deleteSznurowkaStatement.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	public void kupSznurowki(List<Sznurowka> sznurowki, Long idSklepu) {
		ArrayList idList = new ArrayList<Long>();
		int i = 0;
		for(Sznurowka s: sznurowki) {
			idList.add(s.getId());
		}
		try {
			kupSznurowkiStatement.setLong(1, idSklepu);
			kupSznurowkiStatement.setArray(2, (Array)idList);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}
	
	public void sprzedajSznurowke(Long id) {
		
	}

}
